vote:
  minPlayerPercentage: 0.3
  cooldownSeconds: 300
  time:
    enabled: true
  weather:
    enabled: true
deathCoordinates:
  enabled: true
deathInventory:
  enabled: true
home:
  enabled: true
  teleportDelaySeconds: 5